#
# Macro file for "CalSG.cc" 
#
#  5 Block and Calorimeter at the end
#

#
/det/setNbOfLayers 1
/det/setNbOfAbsor  1
/det/setAbsor 1 Aluminium 9 cm
/det/setSizeY 50 cm
/det/setSizeZ 50 cm
#
/det/setBlock 0 -12 cm 18 cm 0 cm 2 cm 10.0 cm 10.0 cm Aluminium  1 

/run/reinitializeGeometry
/run/initialize
/run/beamOn 1

/det/setBlock 0 -10 cm 18 cm 0 cm 2 cm 10.0 cm 10.0 cm Aluminium  1

/run/reinitializeGeometry
/run/initialize
/run/beamOn 1





