#
# Macro file for "CalSG.cc" 
#
#  5 Block and Calorimeter at the end
#

#
/testem/det/setNbOfLayers 1
/testem/det/setNbOfAbsor  1
/testem/det/setAbsor 1 Aluminium 9 cm
/testem/det/setSizeY 50 cm
/testem/det/setSizeZ 50 cm
#
/testem/det/setBlock 0 -12 cm 18 cm 0 cm 2 cm 10.0 cm 10.0 cm Aluminium

/run/reinitializeGeometry
/run/initialize
/run/beamOn 1

/testem/det/setBlock 0 -10 cm 18 cm 0 cm 2 cm 10.0 cm 10.0 cm Aluminium

/run/reinitializeGeometry
/run/initialize
/run/beamOn 1





