#
# Macro file for the initialization phase of "CalSG.cc"
#
# Sets some default verbose
# and initializes the graphic.
#
/control/verbose 0
/run/verbose 0
/tracking/verbose 0


# Use this open statement to create an OpenGL view:
/vis/open OGL 600x600-0+0

# Use this open statement to create a .heprep file suitable for
# viewing in HepRApp:
#/vis/open HepRepFile

/vis/heprep/setOverwrite True
/vis/heprep/setCullInvisibles False

/vis/heprep/setFileName TrajectoryData
/vis/heprep/setFileDir ../Test/


# Disable auto refresh and quieten vis messages whilst scene and
# trajectories are established:
/vis/viewer/set/autoRefresh false
/vis/verbose errors

# Draw geometry:
/vis/drawVolume


/vis/scene/add/trajectories rich
/vis/verbose confirmations



#/vis/modeling/trajectories/create/drawByCharge
#/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true

/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/default/setDrawStepPts true
#/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 5

#/vis/modeling/trajectories/drawByCharge-0/default/setDrawAuxPts true
#/vis/modeling/trajectories/drawByCharge-0/default/setAuxPtsSize 5
#/vis/modeling/trajectories/drawByCharge-0/default/setTimeSliceInterval 0.1 ns







# Re-establish auto refreshing and verbosity:
/vis/viewer/set/autoRefresh true
/vis/verbose warnings

#
# For file-based drivers, use this to create an empty detector view:
#/vis/viewer/flush
/vis/viewer/refresh

# To superimpose all of the events from a given run:
/vis/scene/endOfEventAction accumulate 


