#
# Macro file for "CalSG.cc" 
#
#  5 Block and Calorimeter at the end
#
#
/det/setNbOfLayers 1
/det/setNbOfAbsor  1
/det/setAbsor 1 "Galactic" 1 cm
/det/setSizeY 50 cm
/det/setSizeZ 50 cm
#
/det/setBlock 0 -30 cm 0 cm 0 cm  5. cm 25.0 cm 25.0 cm Aluminium 1 
/det/setBlock 1 -10 cm 0 cm 0 cm 10. cm 25.0 cm 25.0 cm Water     1 

#/det/update

/process/em/verbose 0
/process/eLoss/verbose 0
/event/verbose 0
/control/verbose 0
/run/verbose 0
/tracking/verbose 0

# /testem/phys/addPhysics  emstandard_opt0
/run/setCut 2.5 cm

/run/initialize
/control/execute ../../vis.mac

/gun/particle e-
/gun/energy 1.0 GeV

/tracking/verbose 1
/run/beamOn 1
